config/routes.rb
Rails.application.routes.draw do
  devise_for :funs
  resources :funs, only: [:show]
  resources :value_creaters, only: [:index, :new, :create, :show]
  root "value_creaters#index"
  resources :messages, only: [:index, :new, :create]

  resources :fun do
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
  end

  resources :value_creaters do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
    collection do
      get 'search'
    end
  end


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/fun.rb
class Fun < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  with_options presence: true do
    validates :last_name
    validates :first_name
    validates :gender_id, numericality: { other_than: 0, message: "can't be blank" }
    validates :birth_date
  end

  has_many :messages
  has_one :value_creater

  has_many :relationships, class_name: "Relationship", foreign_key: "fun_id", dependent: :destroy
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "value_creater_id", dependent: :destroy
  has_many :followings, through: :relationships, source: :value_creater
  has_many :followers, through: :reverse_of_relationships, source: :fun

 def follow(value_creater_id)
    relationships.create(value_creater_id: value_creater_id)
 end

 def unfollow(value_creater_id)
    relationships.find_by(value_creater_id: value_creater_id).destroy
 end

 def following?(value_creater)
    followings.include?(value_creater)
 end

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :gender
end

app/models/gender.rb
class Gender < ActiveHash::Base
    self.data = [
      { id: 1, name: '---' },
      { id: 2, name: '男性' },
      { id: 3, name: '女性' },
      { id: 4, name: 'LGBT' }
    ]

    include ActiveHash::Associations
    has_many :funs
    end

app/models/message.rb
class Message < ApplicationRecord
    with_options presence: true do
        validates :type_id, numericality: { other_than: 0, message: "can't be blank" }
        validates :content
    end
    
    belongs_to :fun
    belongs_to :value_creater

    extend ActiveHash::Associations::ActiveRecordExtensions
    belongs_to :type
end

app/models/relationship.rb
class Relationship < ApplicationRecord
    belongs_to :fun, class_name: "Fun"
    belongs_to :value_creater, class_name: "ValueCreater"

    with_options presence: true do
        validates :fun_id
        validates :value_creater_id
     end
end

app/models/type.rb
class Type < ActiveHash::Base
    self.data = [
        { id: 1, name: 'response' },
        { id: 2, name: 'thanks' },
        { id: 3, name: 'job request' },
      ]

      include ActiveHash::Associations
      has_many :messages
      end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/value_creater.rb
class ValueCreater < ApplicationRecord
    with_options presence: true do
        validates :image
        validates :name_workplace
        validates :address_workplace
        validates :introduction
     end

     validates :fun_id, uniqueness: true

     has_many :messages
     belongs_to :fun
     has_one_attached :image

     has_many :relationships, class_name: "Relationship", foreign_key: "fun_id", dependent: :destroy
     has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "value_creater_id", dependent: :destroy
     has_many :followings, through: :relationships, source: :value_creater
     has_many :followers, through: :reverse_of_relationships, source: :fun

    def self.search(search)
      if search != ""
        ValueCreater.where('name_workplace LIKE(?)', "%#{search}%")
      else
        ValueCreater.all
      end
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
   before_action :authenticate_fun!
   before_action :configure_permitted_parameters, if: :devise_controller?

   private

   def configure_permitted_parameters
     devise_parameter_sanitizer.permit(:sign_up,
                                       keys: [:last_name, :first_name, :last_name_kana, :gender_id, :birth_date])
   end
end

app/controllers/funs_controller.rb
class FunsController < ApplicationController
    def show
    end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
    def index
        @funs = current_fun.value_creater.followers
        @value_creaters = current_fun.followings 
    end

    def new
        @funs = current_fun.value_creater.followers
        @value_creaters = current_fun.followings 
        if params[:fun_id]
            @partner_name = Fun.find(params[:fun_id])
            @partner_create_path = Fun.find(params[:fun_id])
        elsif params[:value_creater_id]
            value_creater = ValueCreater.find(params[:value_creater_id])
            @partner_name = value_creater.fun
            @partner_create_path = value_creater
        end
    end

    def create
        message = Message.new

    end

    private

    def message_params
        params.require(:message).permit(:type_id, :content).merge(user_id: current_fun.id)
    end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController

  def create
    value_creater = ValueCreater.find(params[:value_creater_id])
    if value_creater.fun_id != current_fun.id
    current_fun.follow(params[:value_creater_id])
    redirect_to request.referer
    else
      redirect_to request.referer
    end
  end

  def destroy
    current_fun.unfollow(params[:value_creater_id])
    redirect_to request.referer  
  end

  def followers
    value_creater = ValueCreater.find_by(fun_id: params[:fun_id])
    unless value_creater.nil?
       @funs = value_creater.followers
    else
      redirect_to root_path
    end
  end

  def followings
    fun = Fun.find_by(id: params[:fun_id])
    unless fun.nil?
       @value_creaters = fun.followings
    else
      redirect_to root_path
    end
  end

end

app/controllers/value_creaters_controller.rb
class ValueCreatersController < ApplicationController
    def index
        @value_creaters = ValueCreater.all
    end

    def new
        @value_creater = ValueCreater.new
    end

    def create
        @value_creater = ValueCreater.create(value_creater_params)
    end

    def show
        @value_creater = ValueCreater.find(params[:id])
    end

    def search
        @value_creaters = ValueCreater.search(params[:keyword])
    end    

    private
    def value_creater_params
        params.require(:value_creater).permit(:image, :name_workplace, :address_workplace, :introduction).merge(fun_id: current_fun.id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/funs_helper.rb
module FunsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/value_creaters_helper.rb
module ValueCreatersHelper
end

app/views/funs/show.html.erb
<%= render "layouts/header" %>

app/views/layouts/_header.html.erb
  <div class="header">

    <%= link_to root_path do %>
      <%= image_tag("funup.png", class:"header-funup-logo") %>
    <% end %>

    <%= form_with(url: search_value_creaters_path, local: true, method: :get, class: "search-form") do |form| %>
      <form>
        <%= form.text_field :keyword, placeholder: "検索", class: "search-input" %>
      </form>
    <% end %>

    <%= link_to root_path do %>
      <%= image_tag("home-icon.png", class:"header-home-icon") %>
    <% end %>

    <%= link_to fun_followers_path(current_fun.id) do %>
      <%= image_tag("fun-icon.png", class:"header-fun-icon") %>
    <% end %>

    <%= link_to fun_followings_path(current_fun.id) do %>
      <%= image_tag("cheer-icon.png", class:"header-cheer-icon") %>
    <% end %>

    <%= link_to fun_path(current_fun.id) do %>
      <%= image_tag("temporary-storage.png", class:"header-user-icon") %>
    <% end %>

  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Funup</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class='foundation'>
      <%= yield %>
    <div>
  </body>
</html>

app/views/messages/index.html.erb
<%= render "layouts/header" %>
<div class='message-index-foundation'>
    <div class='main-block'>
        <div class='main-upper-block'>
            <div class='upper-left-block'>
            <%= current_fun.last_name %> <%= current_fun.first_name %>
            </div>
            <div class='upper-right-block'>
            相手ユーザーネーム
            <div>
        <div>
        <div class='main-under-block'>
            <div class='under-left-block'>
                <% @funs.each do |fun| %>
                    <%= fun.last_name %> <%= fun.first_name %>
                <% end %>

                <% @value_creaters.each do |creater| %>
                    <div class='message-creater-img'>
                        <%= image_tag creater.image, class: "creater-img" %>
                    </div>

                    <h3 class='message-creater-name'>
                        <%= creater.fun.last_name %> <%= creater.fun.first_name %>
                    </h3>
                <% end %>
            </div>
            <div class='under-right-block'>
            <div>    
        <div>
    </div>
</div>

app/views/messages/new.html.erb
<%= render "layouts/header" %>
<div class='message-index-foundation'>
    <div class='main-block'>
        <div class='main-upper-block'>
            <div class='upper-left-block'>
                <%= current_fun.last_name %> <%= current_fun.first_name %>
            </div>
            <div class='upper-right-block-new'>
                <%= @partner_name.last_name %> <%= @partner_name.first_name %>            
            </div>            
        </div>
        <div class='main-under-block'>
            <div class='under-left-block'>
                <div class='under-left-funs'>
                    <% @funs.each do |fun| %>
                        <div class='each-funs-block'>
                            <%= link_to new_message_path(fun_id: fun.id) do %>
                                <% if !fun.value_creater.nil? %> 
                                    <%= image_tag fun.value_creater.image, class: "message-companion-images" %>
                                <% elsif fun.gender_id == 2 %>
                                    <%= image_tag("man-temporary.png", class:"message-companion-images") %>
                                <% elsif fun.gender_id == 3 %>
                                    <%= image_tag("woman-temporary.png", class:"message-companion-images") %> 
                                <% elsif fun.gender_id == 4 %>
                                    <%= image_tag("lgbt-temporary.png", class:"message-companion-images") %> 
                                <% end %>
                            <% end %>
                            <%= fun.last_name %> <%= fun.first_name %>
                        </div>
                    <% end %>
                </div>
                <div class='under-left-creaters'>
                    <% @value_creaters.each do |creater| %>
                        <div class='each-creaters-block'>
                            <%= link_to new_message_path(value_creater_id: creater.id) do %>
                                <%= image_tag creater.image, class: "message-companion-images" %>
                            <% end %>
                            <%= creater.fun.last_name %> <%= creater.fun.first_name %>
                        </div>
                    <% end %>
                </div>
            </div>
            <div class='under-right-block-new'>
                <div class='new-messages-block'>
                    <div class='partner-left-messages'>
                    </div> 
                    <div class='myself-right-messages'>
                    </div> 
                </div>
                <%= form_with model: @message, url: messages_path(partner_id: @partner_create_path), id: 'new-message-form', class: 'new-message-form', local: true do |f| %>
                    <input type="checkbox" id="message-type-icon-id">
                        <label class="message-type-icon-id" for="message-type-icon-id">    
                            <%= image_tag("type-icon.png", class:"message-type-icon") %>
                        </label>
                        <div class="message-types-block">
                            <%= f.collection_select(:type_id, Type.all, :id, :name, {}, {class:"message-types-select"}) %>                            
                        </div>
                    <%= f.text_field :content, class: 'message-content', placeholder: 'メッセージ...' %>
                    <%= f.submit '送信', class: 'form-submit' %>
                <% end %>
            </div>    
        </div>
    </div>
</div>

app/views/relationships/followers.html.erb
<%= render "layouts/header" %>
<div class='followers-foundation'>
    <% @funs.each do |fun| %>
        <div class='followers-each-fun-block'>
            <%= link_to new_message_path(fun_id: fun.id) do %>
                <% if !fun.value_creater.nil? %> 
                    <%= image_tag fun.value_creater.image, class: "followers-fun-images" %>
                <% elsif fun.gender_id == 2 %>
                    <%= image_tag("man-temporary.png", class:"followers-fun-images") %>
                <% elsif fun.gender_id == 3 %>
                    <%= image_tag("woman-temporary.png", class:"followers-fun-images") %> 
                <% elsif fun.gender_id == 4 %>
                    <%= image_tag("lgbt-temporary.png", class:"followers-fun-images") %> 
                <% end %>
            <% end %>
            <div class='followers-each-fun-texts'>
                <%= fun.last_name %> <%= fun.first_name %>
                <%= fun.gender.name %>
            </div>
        </div>
    <% end %>
</div>

app/views/relationships/followings.html.erb
<%= render "layouts/header" %>
<div class='followings-foundation'>
  <% @value_creaters.each do |creater| %>
    <div class='followings-each-creater-block'>
      <%= link_to value_creater_path(creater) do %>
        <%= image_tag creater.image, class: "followings-creater-images" %>
      <% end %>
      <div class='followings-each-creater-texts'>
        <p> <%= creater.fun.last_name %> <%= creater.fun.first_name %>
        <span class='followings-sentence'> <%= creater.fun.gender.name %> </span> </p>
        <p> <%= creater.name_workplace %> </p>
        <p> <%= creater.address_workplace %> </p>
      </div>
    </div>
  <% end %>
</div>

app/views/value_creaters/index.html.erb
<%= render "layouts/header" %>
<div class='value-creaters-index-foundation'>
  <%= link_to 'ログアウト', destroy_fun_session_path, method: :delete, class: "logout" %>
  <%= link_to '仮新規作成', new_value_creater_path, method: :get, class: "new" %>
  
  <% @value_creaters.each do |creater| %>
    <div class='creaters-each-block'>     
      <%= link_to value_creater_path(creater) do %>
        <%= image_tag creater.image, class: "index-creater-image" %>
      <% end %>
      <div class='each-texts'>
        <p> <%= creater.fun.last_name %> <%= creater.fun.first_name %>
        <span class='sentence'> <%= creater.fun.gender.name %> </span> </p>
        <p> <%= creater.name_workplace %> </p>
        <p> <%= creater.address_workplace %> </p>
      </div>
    </div>
  <% end %>

</div>

app/views/value_creaters/new.html.erb
        <%= render "layouts/header" %>
        
        <%= current_fun.last_name%>
       
        <%= form_with model: @value_creater, url: value_creaters_path, id: 'new_fun', class: 'new_fun', local: true do |f| %>
          <%#<%= render "devise/shared/error_messages", resource: resource %>

          <label class="form-image">
            <span class="image-file">画像</span>
            <%= f.file_field :image, class: 'hidden' %>
          </label>

          <div class='input-name-wrap'>
            <%= f.text_area :name_workplace, class:"value_creater", id:"name_workplace", placeholder:"勤務先" %>
          </div>  

          <div class='input-name-wrap'>
            <%= f.text_area :address_workplace, class:"value_creater", id:"address_workplace", placeholder:"勤務地" %>
          </div> 

          <div class='input-name-wrap'>
            <%= f.text_area :introduction, class:"value_creater", id:"introduction", placeholder:"自己紹介" %>
          </div> 


          <div class="actions">
            <%= f.submit "登録する" %>
          </div>
        <% end %>

app/views/value_creaters/show.html.erb
<%= render "layouts/header" %>
<div class="show-center-block">
  <div class="upper-block">
    <div class='creater-img-content'>
      <%= image_tag @value_creater.image, class: "creater-img" %>
    </div>
  
    <% if current_fun.following?(@value_creater) %>
        <%= link_to 'メッセージを送信', messages_path, class: 'message-btn'%>
        <%= link_to value_creater_relationships_path(@value_creater.id), method: :delete do %>
        <%= image_tag("unfollow.png", class:"fun-btn") %>
        <% end %>
    <% else %>
      <%= link_to value_creater_relationships_path(@value_creater.id), method: :post do %>
        <%= image_tag("fun-btn.png", class:"fun-btn") %>
      <% end %>
    <% end %>

  </div>
  <div class="show-under-block">         
    <div class="first-line">
      <h3 class='creater-name'>
        <%= @value_creater.fun.last_name %> <%= @value_creater.fun.first_name %>
      </h3>
    </div>
    <div class="second-line">
        <%= @value_creater.name_workplace %>
    </div>
    <div class="third-line">
         <%= @value_creater.address_workplace %>
    </div>
    <div class="fourth-line">
         <%= @value_creater.introduction %>
    </div>
</div>          